RecipeFactory/Models/ErrorViewModel.cs
namespace RecipeFactory.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RecipeFactory/Models/Recipe.cs
using System.ComponentModel.DataAnnotations;

namespace RecipeFactoryWeb.Models
{
	public class Recipe
	{
		[Key]
		public int Id { get; set; }
		
		[Required]
		public string Name { get; set; }
		
		[Required]
		public string Ingredients { get; set; }
		
		[Required]
		public string Instructions { get; set; }

		[Required]
		public string Type { get; set; }

		public string? Nutritions { get; set; }

		public string? Image { get; set; }

		public DateTime CreatedDateTime { get; set; } = DateTime.Now;
		
	}
}

RecipeFactory/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;

namespace RecipeFactory.Controllers
{
	public class AdminController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

RecipeFactory/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using RecipeFactory.Models;
using RecipeFactoryWeb.Data;
using RecipeFactoryWeb.Models;

namespace RecipeFactory.Controllers;

public class HomeController : Controller
{
	private readonly ApplicationDbContext _db;

	public HomeController(ApplicationDbContext db)
	{
		_db = db;
	}

	public IActionResult Index()
	{
		IEnumerable<Recipe> objRecipeList = _db.Recipes;
		return View(objRecipeList);
	}

	public IActionResult Privacy()
	{
		return View();
	}

	[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
	public IActionResult Error()
	{
		return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
	}
}

RecipeFactory/Controllers/RecipeController.cs
using Microsoft.AspNetCore.Mvc;
using RecipeFactoryWeb.Data;
using RecipeFactoryWeb.Models;

namespace RecipeFactoryWeb.Controllers;

public class RecipeController : Controller
{
	private readonly ApplicationDbContext _db;

	public RecipeController(ApplicationDbContext db)
	{
		_db = db;
	}

	public IActionResult Index()
	{
		IEnumerable<Recipe> objRecipeList = _db.Recipes;
		return View(objRecipeList);
	}

	public IActionResult RecipeDetail()
	{
		IEnumerable<Recipe> objRecipeList = _db.Recipes;
		return View(objRecipeList);
	}


	public IActionResult SearchResult()
	{
		IEnumerable<Recipe> objRecipeList = _db.Recipes;
		return View(objRecipeList);
	}

	//GET
	public IActionResult Create()
	{
		return View();
	}

	//POST
	[HttpPost]
	[ValidateAntiForgeryToken]
	public IActionResult Create(Recipe obj)
	{
		if (ModelState.IsValid)
		{
			_db.Recipes.Add(obj);
			_db.SaveChanges();
			return RedirectToAction("Index");
		}

		return View(obj);
	}

	//GET
	public IActionResult Edit(int? id)
	{
		if (id == null || id == 0) return NotFound();
		var recipeFromDb = _db.Recipes.Find(id);

		if (recipeFromDb == null) return NotFound();

		return View(recipeFromDb);
	}

	//POST
	[HttpPost]
	[ValidateAntiForgeryToken]
	public IActionResult Edit(Recipe obj)
	{
		if (ModelState.IsValid)
		{
			_db.Recipes.Update(obj);
			_db.SaveChanges();
			return RedirectToAction("Index");
		}

		return View(obj);
	}

	//GET
	public IActionResult Delete(int? id)
	{
		if (id == null || id == 0) return NotFound();
		var recipeFromDb = _db.Recipes.Find(id);

		if (recipeFromDb == null) return NotFound();

		return View(recipeFromDb);
	}

	//POST
	[HttpPost]
	[ValidateAntiForgeryToken]
	public IActionResult DeletePost(int? id)
	{
		var obj = _db.Recipes.Find(id);
		if (obj == null) return NotFound();

		_db.Recipes.Remove(obj);
		_db.SaveChanges();
		return RedirectToAction("Index");
	}
}

RecipeFactory/Views/Admin/Index.cshtml
<html lang="tr">
<body class="sb-nav-fixed">
	<nav class="sb-topnav navbar navbar-expand " style="background-color: #dbe3ed;">
		<!-- Navbar Search-->
		<!-- Navbar-->
	</nav>
	<!--delete-->
<div id="layoutSidenav">
	<div id="layoutSidenav_nav">
		<nav class="sb-sidenav sb-sidenav-dark" style="background-color: #dbe3ed;;color:black;">
			<div class="sb-sidenav-menu ">
				<div class="nav" style="color:black;">
					<div class="sb-sidenav-menu-heading" style="color:black;">Menü</div>
					<a class="nav-link" style="color:black;" asp-controller="Home" asp-action="Index">
						<div class="sb-nav-link-icon"><i class="fas fa-home" style="color:black;"></i></div>
						Ana Sayfa
					</a>
					<div class="sb-sidenav-menu-heading" style="color:black;">İçerik İşlemleri</div>
					<a class="nav-link" style="color:black;" asp-controller="Admin" asp-action="MainCategories">
						<div class="sb-nav-link-icon"><i class="fas fa-graduation-cap" style="color:black;"></i></div>
						Tarifler
					</a>
					<a class="nav-link" style="color:black;" asp-controller="Announcement" asp-action="Announcements">
						<div class="sb-nav-link-icon"><i class="fas fa-bell" style="color:black;"></i></div>
						Kategoriler
					</a>

					<div class="sb-sidenav-menu-heading" style="color:black;">Kullanıcı İşlemleri</div>
					<a class="nav-link" style="color:black;" asp-area="" asp-controller="Admin" asp-action="Roles">
						<div class="sb-nav-link-icon"><i class="fas fa-user-shield" style="color:black;"></i></div>
						Roller
					</a>
					<a class="nav-link" style="color:black;" asp-controller="Admin" asp-action="Users">
						<div class="sb-nav-link-icon"><i class="fas fa-users" style="color:black;"></i></div>
						Kullanıcılar
					</a>
				</div>
			</div>
		</nav>
	</div>
	<div id="layoutSidenav_content">
		<footer class="py-4 bg-light mt-auto">
			<div class="container-fluid">
				<div class="d-flex align-items-center justify-content-between small">
					<div class="text-muted">Copyright &copy; </div>
					<div>
						<a asp-controller="Home" asp-action="Privacy">Gizlilik Sözleşmesi</a>
						&middot;
					</div>
				</div>
			</div>
		</footer>
	</div>
</div>

</body>
</html>

RecipeFactory/Views/Admin/_AdminLayout.cshtml
@{
    ViewData["Title"] = "_AdminLayout";
}

<h1>Admin</h1>

RecipeFactory/Views/Home/Index.cshtml
@model IEnumerable<RecipeFactoryWeb.Models.Recipe>

@{
	ViewData["Title"] = "Home Page";
	var temp = 1;
}

<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
	<div class="carousel-inner rounded-3">
		<div class="carousel-item active">
			<img src="https://loremflickr.com/320/200/pasta,rice?random=1" class="d-block w-100" alt="..." style="height: 550px">
		</div>
		<div class="carousel-item">
			<img src="https://loremflickr.com/320/200/pasta,rice?random=2" class="d-block w-100" alt="..." style="height: 550px">
		</div>
		<div class="carousel-item active">
			<img src="https://loremflickr.com/320/200/pasta,rice?random=3" class="d-block w-100" alt="..." style="height: 550px">
		</div>
		<div class="carousel-item">
			<img src="https://loremflickr.com/320/200/pasta,rice?random=4" class="d-block w-100" alt="..." style="height: 550px">
		</div>
	</div>
	<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
		<span class="carousel-control-prev-icon" aria-hidden="true"></span>
		<span class="visually-hidden">Previous</span>
	</button>
	<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
		<span class="carousel-control-next-icon" aria-hidden="true"></span>
		<span class="visually-hidden">Next</span>
	</button>
</div>

<br/>
<h2>Super Delicious</h2>
<br/>

<div class="row g-4">
	@foreach (var item in Model)
	{
		<div class="col-4">
			<div class="card h-100">
				<a asp-controller="Recipe" asp-action="RecipeDetail" asp-route-id="@item.Id" style="color: black; text-decoration: none">

					<img src="https://loremflickr.com/320/200/pasta,rice?random=\@temp" class="card-img-top" alt="...">
				<div class="card-body">
					<h5 class="card-title">@item.Name</h5>
					<p class="card-text">@item.Type</p>
				</div>
				<div class="card-footer">
					<small class="text-muted">@item.CreatedDateTime</small>
				</div>
				</a>
			</div>
		</div>
		temp++;
	}
</div>

<br/>
<h2>Latest Recipes</h2>
<br/>

<div class="row g-4">
	@foreach (var item in Model)
	{
		<div class="col-3">
			<div class="card h-50">
				<a asp-controller="Recipe" asp-action="RecipeDetail" asp-route-id="@item.Id" style="color: black; text-decoration: none">

					<img src="https://loremflickr.com/320/200/pasta?random=\@temp" class="card-img-top " alt="...">
				<div class="card-body">
					<h5 class="card-title">@item.Name</h5>
				</div>
				</a>
			</div>
		</div>
		temp++;
	}
</div>

RecipeFactory/Views/Recipe/Create.cshtml
@model RecipeFactoryWeb.Models.Recipe

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" enctype="multipart/form-data">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2>Create Recipe</h2>
			<hr />
		</div>
		<div class="mb-3">
			<label asp-for="Name"></label>
			<input asp-for="Name" class="form-control" />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		
		<div class="mb-3">
			<label asp-for="Type"></label>
			<input asp-for="Type" class="form-control" />
			<span asp-validation-for="Type" class="text-danger"></span>
		</div>
		
		<div class="mb-3">
			<label asp-for="Ingredients"></label>
			<input asp-for="Ingredients" class="form-control" />
			<span asp-validation-for="Ingredients" class="text-danger"></span>
		</div>
		
		<div class="mb-3">
			<label asp-for="Instructions"></label>
			<input asp-for="Instructions" class="form-control" />
			<span asp-validation-for="Instructions" class="text-danger"></span>
		</div>
		
		<div class="mb-3">
			<label asp-for="Nutritions"></label>
			<input asp-for="Nutritions" class="form-control" />
			<span asp-validation-for="Nutritions" class="text-danger"></span>
		</div>
		
		<div class="mb-3">
			<label asp-for="Image"></label>
			<input type="file" class="form-control" />
		</div>
		
		<button type="submit" class="btn">Create</button>
		<a asp-controller="Recipe" asp-action="Index" class="btn">Cancel</a>
	</div>
</form>

@section Scripts {
	<partial name="_ValidationScriptsPartial" />
}

RecipeFactory/Views/Recipe/Delete.cshtml
@model RecipeFactoryWeb.Models.Recipe

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" enctype="multipart/form-data" asp-action="DeletePost">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2>Delete Recipe</h2>
			<hr />
		</div>

		<input type="hidden" asp-for="Id" />

		<div class="mb-3">
			<label asp-for="Name"></label>
			<input asp-for="Name" disabled class="form-control" />
		</div>

		<div class="mb-3">
			<label asp-for="Type"></label>
			<input asp-for="Type" disabled class="form-control" />
		</div>
		
		<div class="mb-3">
			<label asp-for="Ingredients"></label>
			<input asp-for="Ingredients" disabled class="form-control" />
		</div>
		
		<div class="mb-3">
			<label asp-for="Instructions"></label>
			<input asp-for="Instructions" disabled class="form-control" />
		</div>
		
		<div class="mb-3">
			<label asp-for="Nutritions"></label>
			<input asp-for="Nutritions" disabled class="form-control" />
		</div>
		
		<div class="mb-3">
			<label asp-for="Image"></label>
			<input asp-for="Image" disabled class="form-control" />
		</div>
		
		<button type="submit" class="btn">Delete</button>
		<a asp-controller="Recipe" asp-action="Index" class="btn">Cancel</a>
	</div>
</form>

@section Scripts {
	<partial name="_ValidationScriptsPartial" />
}

RecipeFactory/Views/Recipe/Edit.cshtml
@model RecipeFactoryWeb.Models.Recipe

@{
	ViewData["Title"] = "Edit";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post" enctype="multipart/form-data">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2>Edit Recipe</h2>
			<hr />
		</div>
		<div class="mb-3">
			<label asp-for="Name"></label>
			<input asp-for="Name" class="form-control" />
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		
		<div class="mb-3">
			<label asp-for="Type"></label>
			<input asp-for="Type" class="form-control" />
			<span asp-validation-for="Type" class="text-danger"></span>
		</div>
		
		<div class="mb-3">
			<label asp-for="Ingredients"></label>
			<input asp-for="Ingredients" class="form-control" />
			<span asp-validation-for="Ingredients" class="text-danger"></span>
		</div>
		
		<div class="mb-3">
			<label asp-for="Instructions"></label>
			<input asp-for="Instructions" class="form-control" />
			<span asp-validation-for="Instructions" class="text-danger"></span>
		</div>
		
		<div class="mb-3">
			<label asp-for="Nutritions"></label>
			<input asp-for="Nutritions" class="form-control" />
			<span asp-validation-for="Nutritions" class="text-danger"></span>
		</div>
		
		<div class="mb-3">
			<label asp-for="Image"></label>
			<input type="file" class="form-control" />
		</div>
		
		<button type="submit" class="btn">Update</button>
		<a asp-controller="Recipe" asp-action="Index" class="btn">Cancel</a>
	</div>
</form>

@section Scripts {
	<partial name="_ValidationScriptsPartial" />
}

RecipeFactory/Views/Recipe/Index.cshtml
@model IEnumerable<RecipeFactoryWeb.Models.Recipe>

@{
	ViewData["Title"] = "Index";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-end">
	<a class="btn btn-primary " asp-controller="Recipe" asp-action="Create">Create Recipe</a>
</div>

<table class="table table-borderless table-striped">
	<thead>
	<tr>
		<th>
			Name
		</th>
		<th>
			Ingredients
		</th>
		<th>
			Instructions
		</th>
		<th>
			Type
		</th>
		<th>
			Nutritions
		</th>
		<th>
			Image
		</th>
		<th>
			Btn
		</th>
	</tr>
	</thead>
	<tbody>
	@foreach (var item in Model)
	{
		<tr>
			<td>
				@item.Name
			</td>
			<td>
				@item.Ingredients
			</td>
			<td>
				@item.Instructions
			</td>
			<td>
				@item.Type
			</td>
			<td>
				@item.Nutritions
			</td>
			<td>
				@item.Image
			</td>
			<td>
				<a class="btn btn-secondary" asp-controller="Recipe" asp-action="Edit" asp-route-id="@item.Id">Edit Recipe</a>
				<a class="btn btn-danger" asp-controller="Recipe" asp-action="Delete" asp-route-id="@item.Id">Delete Recipe</a>
			</td>
		</tr>
	}
	</tbody>
</table>

RecipeFactory/Views/Recipe/RecipeDetail.cshtml
@using RecipeFactoryWeb.Models
@model IEnumerable<RecipeFactoryWeb.Models.Recipe>

@{
    ViewData["Title"] = "RecipeDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
	var item = Model.FirstOrDefault();
}

<div class="card text-white w-100 border-0">
	<img src="https://loremflickr.com/940/300/pasta,rice?random=1" class="card-img" alt="...">
	<div class="card-img-overlay">
		<h1 class="card-title align-text-bottom">@item.Name</h1>
	</div>
</div>

<div class="container mt-5">
	<div class="row">
		<div class="col-4">
			<h5 class="ps-3">Ingredients</h5>
			<ul class="list-group list-group-flush w-25 border-0">
				<li class="list-group-item text-center">@item.Ingredients</li>
			</ul>
		</div>
		<div class="col-8">
			<h5>Instructions</h5>
			<ol class="list-group list-group-numbered">
				<li class="list-group-item">@item.Instructions</li>
			</ol>
			<h5 class="pt-5">Nutrient Facts</h5>
			<ol>
				<li>@item.Nutritions</li>
			</ol>
		</div>
	</div>
</div>

RecipeFactory/Views/Recipe/SearchResult.cshtml
@model IEnumerable<RecipeFactoryWeb.Models.Recipe>

@{
    ViewData["Title"] = "SearchResult";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>SearchResult</h1>

RecipeFactory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<title>@ViewData["Title"] - RecipeFactory</title>
	<!-- Font Awesome -->
	<link
		href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
		rel="stylesheet"/>
	<!-- Google Fonts -->
	<link
		href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
		rel="stylesheet"/>
	<!-- MDB -->
	<link
		href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.0.1/mdb.min.css"
		rel="stylesheet"/>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
	<link rel="stylesheet" href="~/css/bootstrap.min.css"/>
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
	<link rel="stylesheet" href="~/RecipeFactory.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
	<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
		<div class="container-fluid">
			<a class="navbar-brand ms-5" asp-area="" asp-controller="Home" asp-action="Index">Recipe Factory</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
				<a class="btn btn-success" asp-controller="Recipe" asp-action="Index">Recipes</a>
				<div class="collapse navbar-collapse d-flex justify-content-center" id="navbarSupportedContent">
					<form class="d-flex">
						<input class="form-control me-sm-2" type="text" placeholder="Search">
						<button class="btn btn-light my-2 my-sm-0" type="submit">
							<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
								<path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
							</svg>
						</button>
					</form>
				</div>
			<div>
				<a asp-controller="Admin" asp-action="Index" class="btn btn-light">
					<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
						<path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0Zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4Zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10Z"/>
					</svg>
				</a>
			</div>
		</div>
	</nav>
</header>
<div class="container">
	<main role="main" class="pb-3">
		@RenderBody()
	</main>
</div>

<div class="container">
	<footer class="py-5 rounded" style="background-color: darksalmon">
		<div class="row d-flex justify-content-center">
			<div class="d-flex justify-content-center ">
				<form>
					<h1 class="text-center">Deliciousness</h1>
					<h1 class="text-center">to your inbox</h1>
						<br />
					<h5 class="text-center">Enjoy weekly hand picked recipes and</h5>
					<h5 class="text-center">recommendations</h5>
					<div class="row">
						<input id="newsletter1" type="text" class="form-control w-75 col-10" placeholder="Email address">
						<button class="btn btn-secondary col-2" type="button">Join</button>
					</div>
				</form>
			</div>
		</div>

		<div class="d-flex justify-content-center">
			<p>By joining our newsletter you agree to our Terms and Conditions</p>
		</div>
	</footer>
</div>

<!-- MDB -->
<script
	type="text/javascript"
	src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.0.1/mdb.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", false)
</body>
</html>